### ISSUE TITLE
MongoId 5 compatibility

### ISSUE THREAD

**Issue by ztmdsbt** [PerfectMemory/mongoid-multitenancy#17]
Found an issue in using MongoId 5:
mongoid/multitenancy.rb:11:
```
def mongoid4?
  MongoId::VERSION.start_with? '4'
end
```
I change the number to '5', it works well with mongoid 5. but I didn't test all things.

Could you update this GEM to work with MongoId 5?

**Comment by chaomao** [comment]
yes, I also need it. 
Please update code and release it, thanks

**Comment by abrisse** [comment]
Fixed in 8c7582b9061631f93e825c3c6ba961e18e56d27f

**Comment by ztmdsbt** [comment]
Thank you very much :)

**Comment by abrisse** [comment]
I have release a new version 1.0.0. Please read carefully the changelog before upgrading.
