### ISSUE TITLE
Devise issue with multiple Tenants

### ISSUE THREAD

**Issue by kschutt** [PerfectMemory/mongoid-multitenancy#20]
I am having a weird issue with Devise and mongoid-multitenancy where the current tenant seems to get _stuck_ for my `user` devise model.

```
class User
    include Mongoid::Document
    include Mongoid::Multitenancy::Document
    tenant(:tenant)
    ...
end
```

When I sign in on my `public` tenant and I inspect the resulting object, it looks as though it is trying to connect to my `test` tenant instead of my `public` tenant. However, there are times where this is reversed and my `test` tenant is trying to connect to my `public` tenant. I can generally force this to happen if I purposefully throw an error on one of the tenants during sign in.

Do I need to set the tenant somewhere in Devise to ensure that it is actually getting the right user? I have noticed that when it gets stuck on the wrong tenant, I can no longer sign in as a user for the current tenant.

Also, if a user exists for both tenants with different passwords, I still get a "signed in successfully" notification if i use the password of the other tenant. However, I am not actually signed in because I can't access any resources.

**Comment by abrisse** [comment]
Hi @kschutt, did you set a `before_filter` in your application controller?

Like:

```ruby
class ApplicationController < ActionController::Base
  before_action :set_client

  # Set the current tenant by parsing the URL
  def set_client
    Mongoid::Multitenancy.current_tenant = Tenant.find_by(host: params[:client_host])
  end
end
```

If you want to select the current tenant thanks to a user, you can reset the current tenant in a before_filter and setting it after the auth using `Mongoid::Multitenancy.current_tenant = current_user.tenant`

**Comment by kschutt** [comment]
I should have noted that this happens specifically with users who have accounts on multiple tenants with the same email. However, when this happens it effects other users as well since it forces authentication through on particular tenant. If the user does not have an account on that tenant, then they receive an error from Devise that the email or password is invalid.

Thanks for the response. Yes, I have that in my application controller. I was able to narrow it down to the create method for `Devise::SessionsController` specifically the `warden.authenticate` line as the query seems to sometimes grabs the user from the wrong tenant.

	def create
		self.resource = warden.authenticate!(auth_options)
		# raise Mongoid::Multitenancy.current_tenant.to_yaml
		set_flash_message(:notice, :signed_in) if is_flashing_format?
		sign_in(resource_name, resource)
		yield resource if block_given?
		respond_with resource, location: after_sign_in_path_for(resource)
	end

For some reason the Tenant is being switched somewhere in Devise I feel, here is my process to reproduce the problem that I am having. It should also be noted that this only happening with users that have the same email in multiple tenants, but the "switching of tenants" effects all users. There are two different user objects and two different tenants. At initial startup, I am able to log into both sites successfully until there is an error.

1. Uncomment the "raise" line in the code above.
2. Login to `tenant_one` with email "test@example.com" and "Password1"
3. A RuntimeError should be thrown displaying the tenant information for `tenant_one`
4. Comment the "raise" line in the code and reload the page
5. This user should be logged in successfully to `tenant_one`
6. Attempt to login to `tenant_two` with "test@example.com" and "Password2"
7. Devise throws the error "Invalid email or password."
8. Uncomment the "raise" line and reload the page
9. A RuntimeEroor should be thrown displaying the tenant information for `tenant_two`
10. Comment the "raise" line in the code and reload the page
11. The page should go back to the login page throwing the "Invalid email or password" message
12. Click "Login" again, and the user now successfully logs into `tenant_two`

Here is the query for trying to log into `tenant_two` that causes Devise to return unauthorized because it is looking in the wrong tenant for the user.

    QUERY  database=development collection=users selector={"$query"=>{"deleted_at"=>nil, "tenant_id"=>"tenant_one", "email"=>"test@example.com"}, "$orderby"=>{"email"=>1}} flags=[:slave_ok] limit=-1 skip=0 batch_size=nil fields=nil (1.0002ms)

**Comment by abrisse** [comment]
Could you write the code portion where you set the current tenant? Thanks.

What server application are you using? Puma? Passenger? Webrick?

**Comment by kschutt** [comment]
This is happening in both Passenger on production and Webrick for development.

	def set_current_client
		subdomain = request.host.split(".")[0]
		if Tenant.fetch_tenant(subdomain)
			current_tenant = Tenant.fetch_tenant(subdomain)
		else 
			current_tenant = Tenant.default
		end
		Mongoid::Multitenancy.current_tenant = current_tenant
	end

**Comment by abrisse** [comment]
Could not reproduce the problem.
