### ISSUE TITLE
N+1 query issue after 1.0

### ISSUE THREAD

**Issue by hanystudy** [PerfectMemory/mongoid-multitenancy#21]
Hi, there

We got N+1 query issue because of the code below after upgraded from 0.4.x to 1.0+:
```ruby
after_initialize lambda {
  if Multitenancy.current_tenant && send(association.to_sym).nil? && new_record?
    send "#{association}=".to_sym, Multitenancy.current_tenant
  end
}
```
There is one more query when running send(association.to_sym).nil?, and it seems not working even use eager loading query in mongoid like:
```ruby
Person.includes(:address).all.to_a
```

My guess is :after_initialize has some conflicts with eager loading, any thought on this?

**Comment by abrisse** [comment]
Hi,

Indeed. It is due to the fact that the default scope set the tenant_id field and that mongoid run a query when accessing to the tenant field.

I have push a new commit that may fix the problem (5ebd4e37bf0af742b871472281de5e052cf86a7b). Could you try it and give me a feedback?

Thanks
