### ISSUE TITLE
Example usage for additional class relations

### ISSUE THREAD

**Issue by serhatbolsu** [PerfectMemory/mongoid-multitenancy#22]
Hello,

In a class that has tenant model;
I use other relations `belongs_to` `has_many`. Can you please add examples how to use ;

```
:class_name, etc. : all the other options will be passed to the mongoid relation (belongs_to)
```

**Comment by abrisse** [comment]
Hello,

See the [Mongoid Metadata object](https://docs.mongodb.org/ecosystem/tutorial/mongoid-relations/#the-metadata-object) for all these options. What it means is that you can use `tenant` exactly like a `belongs_to` relation.
