### ISSUE TITLE
Incompatible with rails 5

### ISSUE THREAD

**Issue by narutosanjiv** [PerfectMemory/mongoid-multitenancy#24]
Rails comes with default required for belongs_to relationship. This gem does not cater to this one. 
There is 'optional' option in 'belongs_to' relationship but it is taken as MULTITENANCY_OPTIONS in current implementation, need to change current implementation.

**Comment by abrisse** [comment]
Fixed in 8c7582b9061631f93e825c3c6ba961e18e56d27f
