### ISSUE TITLE
tenant applying two organization with "$and" in query criteria

### ISSUE THREAD

**Issue by aashishgarg** [PerfectMemory/mongoid-multitenancy#35]
* mongoid-multitenancy - 2.0.3
* mongoid version - 7.3.4
* ruby version - ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
* rails version - 6.0.4
* Browser - Chrome 103.0.5060.134 (Official Build) (64-bit)
* OS - Ubuntu 20.04.4 LTS
-----------
We have a user model as -
 
```
  class User
    include Mongoid::Document
    include Mongoid::Multitenancy::Document
    tenant :organization
    
    def root_admin?
        HierarchyNode.where(organization: organization, parent_node_id: nil).first
    end
  end
```

When multiple users from different organizations are logged in then **sometimes** this query is adding other user's organization filter as well in where query with "$and" which should not be the case. But sometimes it works as expected.

`#<Mongoid::Criteria
  selector: {"organization_id"=>BSON::ObjectId('62cffd3166b207d96a47de76'), "is_deleted"=>{"$ne"=>true}, "$and"=>[{"organization_id"=>BSON::ObjectId('559a23c269702d43a900002f')}], "parent_node_id"=>nil}
  options:  {}
  class:    HierarchyNode
  embedded: false>
`

**Comment by ajayakodi-wm** [comment]
@abrisse, @sroucheray , @jperville , @vtabary  Any idea about the above issues?

**Comment by abrisse** [comment]
It seems the problem may be caused by a leak of the current tenant in your application and it not related to the gem itself. `mongoid-multitenancy` is thread-safe.

**Comment by ashish-watermark** [comment]
> Can you share your `HierarchyNode` class? In particular, is it tenanted by `organization`?
> 
> In the case it is, and if you have a `current_tenant` set, then you probably shouldn't add `where(organization: organization), since mongoid-multitenancy is already doing that for you transparently.

```
class HierarchyNode
  include Mongoid::Document
  include Mongoid::Multitenancy::Document

  tenant :organization

end
```
